// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_FLVqOGb_RqSDR6Ya_rt3BpNjxQvQmRI',
    appId: '1:607277774244:web:72fdc0710b97b07f5ebd31',
    messagingSenderId: '607277774244',
    projectId: 'coffee-shop-app-93f5b',
    authDomain: 'coffee-shop-app-93f5b.firebaseapp.com',
    storageBucket: 'coffee-shop-app-93f5b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdCVvZ16zkG6xAUP9V7DFIILSLEhQA6f0',
    appId: '1:607277774244:android:02c7d456720976e65ebd31',
    messagingSenderId: '607277774244',
    projectId: 'coffee-shop-app-93f5b',
    storageBucket: 'coffee-shop-app-93f5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlrVosrztZFluveks1KJWfkIpXKw08SM4',
    appId: '1:607277774244:ios:73d886448e54823e5ebd31',
    messagingSenderId: '607277774244',
    projectId: 'coffee-shop-app-93f5b',
    storageBucket: 'coffee-shop-app-93f5b.firebasestorage.app',
    iosBundleId: 'com.example.coffeeShopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlrVosrztZFluveks1KJWfkIpXKw08SM4',
    appId: '1:607277774244:ios:73d886448e54823e5ebd31',
    messagingSenderId: '607277774244',
    projectId: 'coffee-shop-app-93f5b',
    storageBucket: 'coffee-shop-app-93f5b.firebasestorage.app',
    iosBundleId: 'com.example.coffeeShopApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_FLVqOGb_RqSDR6Ya_rt3BpNjxQvQmRI',
    appId: '1:607277774244:web:dcff504753633dd65ebd31',
    messagingSenderId: '607277774244',
    projectId: 'coffee-shop-app-93f5b',
    authDomain: 'coffee-shop-app-93f5b.firebaseapp.com',
    storageBucket: 'coffee-shop-app-93f5b.firebasestorage.app',
  );
}
